language : node_js
node_js:
  - "10"
  - "9"
install:
  - npm install
os:
  - linux

cache:
  directories:
    - ./node_modules

stages:
  - name: deploy

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

jobs:
  include:
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version
        - npm run build
        - echo "NPM Building Finished."
      before_deploy: "cd dist/recordinfo"
      deploy:  
        provider: npm
        email: 1061427304@qq.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
      after_deploy: "echo 'publish finish'"
