language : node_js
node_js:
 - "10"
 - "9"
install:
- npm install
os:
 - linux

stages:
 - test
 - name: deploy

jobs:
 include:
   - stage: test
     script:
       - node --version
       - npm --version

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
       - npm run build
       - echo "NPM Building Finished."
       - cd dist/recordinfo

     deploy:
       provider: npm
       email: 1061427304@qq.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true
